
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Facilitiestemp\Desktop\Test\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("933x563")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 563,
    width = 933,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    243.0,
    50.0,
    image=image_image_1
)

canvas.create_text(
    104.0,
    19.0,
    anchor="nw",
    text="MO1234567",
    fill="#FFFFFF",
    font=("ArialMT", 48 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    556.0,
    50.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    465.0,
    265.0,
    image=image_image_3
)

canvas.create_text(
    597.0,
    39.0,
    anchor="nw",
    text="Alex Fernan F. Mercado",
    fill="#343A40",
    font=("Roboto Bold", 20 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=712.0,
    y=468.0,
    width=172.0,
    height=58.0
)

canvas.create_text(
    66.0,
    147.0,
    anchor="nw",
    text="Main Operation",
    fill="#343A40",
    font=("Arial BoldMT", 24 * -1)
)

canvas.create_text(
    64.0,
    173.0,
    anchor="nw",
    text="Wirebond/3RD Opt. Insp.",
    fill="#868E96",
    font=("ArialMT", 32 * -1)
)

canvas.create_text(
    68.0,
    267.0,
    anchor="nw",
    text="Device",
    fill="#343A40",
    font=("Arial BoldMT", 24 * -1)
)

canvas.create_text(
    66.0,
    295.0,
    anchor="nw",
    text="PM9:0001234",
    fill="#868E96",
    font=("ArialMT", 32 * -1)
)

canvas.create_text(
    526.0,
    143.0,
    anchor="nw",
    text="Package",
    fill="#343A40",
    font=("Arial BoldMT", 24 * -1)
)

canvas.create_text(
    526.0,
    170.0,
    anchor="nw",
    text="SOT",
    fill="#868E96",
    font=("ArialMT", 32 * -1)
)

canvas.create_text(
    528.0,
    268.06951904296875,
    anchor="nw",
    text="Customer",
    fill="#343A40",
    font=("Arial BoldMT", 24 * -1)
)

canvas.create_text(
    528.0,
    296.0,
    anchor="nw",
    text="TPC",
    fill="#868E96",
    font=("ArialMT", 32 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    163.0,
    474.0,
    image=image_image_4
)

canvas.create_text(
    129.0,
    434.0,
    anchor="nw",
    text="MO Qty.",
    fill="#FFFFFF",
    font=("ArialMT", 20 * -1)
)

canvas.create_text(
    64.0,
    457.0,
    anchor="nw",
    text="1234567",
    fill="#FFFFFF",
    font=("Arial BoldMT", 48 * -1)
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    479.0,
    474.0,
    image=image_image_5
)

canvas.create_text(
    400.0,
    439.0,
    anchor="nw",
    text="Remaining MO Qty.",
    fill="#FFFFFF",
    font=("ArialMT", 19 * -1)
)

canvas.create_text(
    383.0,
    458.0,
    anchor="nw",
    text="1234567",
    fill="#FFFFFF",
    font=("Arial BoldMT", 48 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=712.0,
    y=468.0,
    width=172.0,
    height=58.0
)
window.resizable(False, False)
window.mainloop()
