name: My GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./path_to_your_code

      - name: Run Python script
        run: python your_script.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
